services:
  mlflow:
    image: bitnami/mlflow:latest
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlruns.sqlite
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
    volumes:
      - mlruns:/mlruns
      - ./mlruns.sqlite:/mlruns.sqlite
    ports:
      - "5000:5000"
    environment:
      MLFLOW_EXPERIMENT_NAME: churn-training

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - mlruns:/app/mlruns     # compartilha registry
      - ./models:/app/models   # transformer local

volumes:
  mlruns: