name: CI & Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - run: pip install -r requirements.txt
      - run: |
          python - << 'PY'
          import mlflow, json, pathlib
          print("✔️  dependências ok – MLflow", mlflow.__version__)
          PY

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t churn-api:pr-${{ github.run_number }} .